# Generated by Django 4.0.4 on 2022-05-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="note",
            field=models.TextField(max_length=5000),
        ),
    ]
